sudo: required
addons:
  chrome: stable
language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "3.5"
install:
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda

  # Useful for debugging any issues with conda
  - conda info -a

  # Install Python and required packages.
  - conda env create -f environment.yml
  - source activate curve-fitting-talk

  # Install reveal-md
  - npm install -g reveal-md


script:
  # Create the docs directory. This is where we will be publishing from
  # (see the "deploy" section below).
  # - mkdir -p docs/images
  # - mkdir -p docs/_assets

  # Create QR codes using scripts.py.
  - make qr
  - make render

  # Copy over the necessary things into the docs/ folder.
  - cp -r images/* docs/images/.
  - cp custom.css docs/_assets/.

  # # Use reveal-md to build the slides
  - reveal-md slides.md --static docs --disable-auto-open --css static/custom.css --theme white --featured-slide 1 --static-dirs=static
  - reveal-md slides.md --print docs/slides.pdf --disable-auto-open --theme white --css static/custom.css

  # Fix the "docs" _assets bug.
  # Specifically: gh-pages doesn't recognize folders that are prefixed by an
  # underscore. This means that _assets is not discoverable in the live page.
  # - cd ./docs
  # - mv _assets assets  # remove underscore
  # - sed -i 's/_assets/assets/g' index.html  # change underscore in index.


# This is an example to deploy to a branch through Travis.
deploy:
  provider: pages
  skip-cleanup: true
  # Set in the settings page of your repository, as a secure variable
  github-token: $GITHUB_TOKEN
  # setting to false force pushes, preventing a bloated repository.
  keep-history: false
  # We read the master branch
  on:
    branch: master
  # Take the docs/ directory
  local-dir: docs
  # Publish to the gh-pages branch
  target-branch: gh-pages
  verbose: true
