name: curve-fitting-talk
channels:
- defaults
- conda-forge
- ericmjl
dependencies:
- python=3.6
- nodejs
- pandoc
- jupyterlab
- pymc3
- matplotlib
- pandas
- holoviews
- bokeh
- ipywidgets
- cython
- click
- jupyter_contrib_nbextensions
- datashader
- pyjanitor
- pip:
  - git+https://github.com/heuer/pyqrcode.git
  - pypng
